// <auto-generated />
namespace Devbazaar.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TaskCategoryredundancy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskCategoryredundancy));
        
        string IMigrationMetadata.Id
        {
            get { return "202101061055137_Task-Category-redundancy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
